# Generated by Django 5.2.1 on 2025-05-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_goal_title_goal_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='due_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Untitled Goal', max_length=200),
        ),
    ]
